# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['MarianMT_Script.py'],
             pathex=['E:\\206309_Gann_Kevin\\git\\Text-To-Text\\MarianMT'],
             binaries=[],
             datas=[('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\tqdm', 'tqdm\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\tqdm-4.50.2.dist-info', 'tqdm-4.50.2.dist-info\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\regex', 'regex\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\regex-2021.4.4.dist-info', 'regex-2021.4.4.dist-info\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\sacremoses', 'sacremoses\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\sacremoses-0.0.43.dist-info', 'sacremoses-0.0.43.dist-info\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\requests', 'requests\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\requests-2.24.0.dist-info', 'requests-2.24.0.dist-info\\'), 
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\packaging', 'packaging\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\packaging-20.4.dist-info', 'packaging-20.4.dist-info\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\filelock-3.0.12.dist-info', 'filelock-3.0.12.dist-info\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\numpy', 'numpy\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\numpy-1.19.1.dist-info', 'numpy-1.19.1.dist-info\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\tokenizers', 'tokenizer\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\tokenizers-0.10.1-py3.8-win-amd64.egg-info', 'tokenizers-0.10.1-py3.8-win-amd64.egg-info\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\torch', 'torch\\'),
			 ('C:\\ProgramData\\Anaconda3\\envs\\MarianMT\\Lib\\site-packages\\torch-1.6.0.dist-info', 'torch-1.6.0.dist-info\\')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='MarianMT_Script',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
